name: build

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 16

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew projects clean build jacocoTestReport --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1.5.2
        with:
          flags: unittests
          fail_ci_if_error: true
